services:
  database-1:
    container_name: database_orig
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - db1.env
  database-2:
    container_name: database_copy
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    env_file:
      - db2.env